### ISSUE TITLE
关于MCMC黑盒攻击

### ISSUE THREAD

**Issue by xxxmian** [LC-John/Fashion-MNIST#6]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/34122441/55275868-78fa2480-5327-11e9-978f-33a714654a2e.png">

**Comment by LC-John** [comment]
1. 是我写错了，应该是u>C(...)[...]则拒绝
2. MCMC是利用Markov chain来进行Monte Carlo采样，Monte Carlo是要基于概率的，所以是u \sim U(0,1)的随机变量
